- contracts/src/Rollup.sol
Core changes:
- Remove hardhat/console import in Rollup.sol
> Remove hardhat/console import in Rollup.sol

- clients/geth/specular/rollup/services/validator/validator.go
Core changes:
- Fix the challenge part in the validator
Notes:
- These changes are inside `rogue_validator.go` in previous version but skipped when porting to public repo
> Fix challenge part in validator

- clients/geth/specular/rollup/services/sequencer/sequencer.go
Core changes:
-Modifies sequencingLoop to use a timer
-Each batch gets added to a batchTxs, and then every timer interval those batches get processed
> modify sequencingLoop in sequencer

- clients/geth/specular/rollup/services/sequencer/sequencer.go
Core changes:
-Use blocks instead of batches in sequencer
> use blocks instead of batches in sequencer

- clients/geth/specular/rollup/services/validator/validator.go
Core changes:
- Fix behavior when validation failed
- Challenge when vmhash or gas mismatch
- Retry when inbox not fully synced
- Panic when other errors happen
- TODO: recover from other errors and retry
> [fix] fix validation retry

- clients/geth/specular/.gitignore
- clients/geth/specular/README.md
Core changes:
- Update Readme for deploying L2
> Update README paths

- clients/geth/specular/README.md
- clients/geth/specular/rollup/services/sequencer/sequencer.go
- clients/geth/specular/rollup/services/utils.go
- clients/geth/specular/rollup/services/validator/validator.go
Core changes: 
- Error Handling improved, and all the errors will be returned upstream and processed. Currently they were being logged only
> Return errors upstream instead of panicking

- contracts/src/SequencerInbox.sol
Remove unnecessary code in Sequencer.
> Sequencer cleanup

- contracts/hardhat.config.ts
updates hardhat config to add support for chiado testnet.
> updated config for chiado

- .editorconfig
configure .editorconfig for go & sol
> adds editorconfig

- clients/geth/specular/rollup/services/sequencer/sequencer.go
Core changes:
- Fix sequencer batching functionality due to incorrect transaction filtering
- Sequencer is able to commit transaction to l2 blockchain now as before
> Fix sequencer batching functionality

- clients/geth/specular/sbin/start_indexer.sh
- clients/geth/specular/sbin/start_sequencer.sh
- clients/geth/specular/sbin/start_validator.sh
Core changes:
- Modify script params for running L2 locally
> modify script params

- contracts/src/Rollup.sol
> [bugfix] Fix slashing bug in challenge completion callback

- docker/envs/blockscout.env
Core changes:
- Customize blockscout
> Customize blockscout

- docker/README.md
- docker/services/docker-compose-l1hardhat.yml
- docker/services/docker-compose-l2geth.yml
Core changes:
- Fix typos in docker files and readme
> Fix docker typo

- clients/geth/specular/README.md
Core changes:
* adds documentation on how to generate the `genesis.json` when running a local network
> update local network docs

- contracts/src/SequencerInbox.sol
- contracts/test/SequencerInbox.t.sol
- contracts/test/utils/Utils.sol
* adds a test for `SequencerInbox.verifyTxInclusion`
* fixes the tx Data hashing in `SequencerInbox.appendTxBatch`
> Sequencer inbox `verifyTxInclusion`

- .github/workflows/slither.yml
Core changes:
- Ignore tests in the slither GH Action
> pass ignore paths to slither

- .github/workflows/e2e.yml
- clients/geth/specular/Dockerfile
- clients/geth/specular/sbin/export_genesis.sh
- contracts/Dockerfile
- contracts/deploy/l1/02_deploy_Rollup.ts
Core changes:
currently the e2e test uses a hardcoded genesis hash. this PR changes the test to dynamically generate the hash from the genesis file
> dynamic genesis hash in e2e test

- .dockerignore
- clients/geth/specular/Dockerfile
- contracts/.dockerignore
- contracts/Dockerfile
Core changes:
- Fix dockerfiles
- Move `.dockerignore` to correct place
Notes:
- Write notes here
> Fix docker 

- contracts/package.json
- contracts/scripts/forge-test-names.ts
- contracts/test/Rollup.t.sol
- contracts/test/SequencerInbox.t.sol
Refactor existing tests to follow style guide:
https://www.notion.so/specular/solidity-development-a8130ee6645d489fa1af58b478241aad?pvs=4
> [Testing] Refactor tests

- .github/workflows/test.yml
Check forge test names in github workflow
- Describe changes here
Add github action to check-forge-names script
> check forge-test-names

- contracts/.eslintrc.json
Core changes:
- Mark the .eslintrc.json as the root config so ESLint stops looking at parent directories for configs.
> Mark .eslintrc.json as root config

- contracts/deploy/l1/02_deploy_Rollup.ts
- contracts/src/IRollup.sol
- contracts/src/Rollup.sol
- contracts/src/pre-deploy/Faucet.sol
- contracts/test/Rollup.t.sol
- contracts/test/SequencerInbox.t.sol
- pnpm-lock.yaml
Core changes:
Add validator whitelist to prevent other actors from calling state-modifying functions.
I've done some basic testing, if this draft looks good, I'll add checks to validator functions and test.
> add validator whitelist

- clients/geth/specular/rollup/rpc/eth/txmgr/tx_mgr.go
- clients/geth/specular/rollup/service.go
- clients/geth/specular/utils/log/log.go
- clients/geth/specular/utils/log/root.go
Adds more context to txmgr logs (taken from bedrock)
> Tx mgr logging

- .gitmodules
- contracts/scripts/bridge/confirm_oracle.ts
- contracts/scripts/bridge/createERC20Token.ts
Core changes:
- Bridge UI updated to react
Areas to review:
- React Hooks
- Stepper View
Steps to Test locally:
1. Start L1 using ganache, hardhat doesn't support `eth_getProof` currently
```sh
npm install ganache --global
ganache --chain.chainId 31337 -b 2 -m "test test test test test test test test test test test junk"
```
2. run L1 migrations
```sh
npx hardhat deploy --tags L1 --network localhost
```
3. start sequencer
```sh
./start_sequencer.sh
```
4. run L2 migrations
```sh
npx hardhat deploy --tags L2 --network specularLocalDev
```
5. Go to Bridge Frontend & Install project dependencies:
```sh
./start.sh 
```
6. For imitating relayer (confirming oracle) run 
```sh
./contracts/scripts/confirm_oracle.ts
```
7. For deploying ERC20 token run 
```sh …
```
> Bridge Frontend Added

- clients/geth/specular/rollup/rpc/bridge/serialization.go
Core changes:
- I mistakenly changed `MethodNumBytes` from `4` -> `5`, reverting this.
Notes:
- Write notes here
> Fix Failing TX Batch

- .github/workflows/release-snapshot.yml
Core changes:
- Add building step before publishing to fix sdk publish failure
> Fix snapshot release workflow

- .gitmodules
> Hook in Magi Submodule

- contracts/deploy/utils/index.ts
> log block info in deploy script

- sbin/create_genesis.sh
- sbin/start_l1.sh
- cd back into cwd
- remove unnecessary env variable
> fix start_l1.sh script

- Makefile
- README.md
- config/example/.genesis.env
- config/local_devnet/base_sp_local_devnet.json
- contracts/hardhat.config.ts
- contracts/scripts/config/create_config.ts
- contracts/scripts/config/create_genesis.ts
- pnpm-lock.yaml
- sbin/create_genesis.sh
- sbin/deploy_l1_contracts.sh
- sbin/start_l1.sh
- sbin/start_sp_geth.sh
See #216
Also changes the ordering of scripts to run; README has been updated accordingly
> Use l1 safe block for l2 genesis timestamp

- README.md
- docs/development.md
- docs/system.md
- sbin/deploy_l1_contracts.sh
- sbin/start_sp_geth.sh
- Adds `-c` to clean workspace in local dev scripts
- Some more minor README cleanup
> Add clean flag to scripts

- README.md
- services/sidecar/rollup/derivation/batch_builder.go
- services/sidecar/rollup/services/disseminator/batch_disseminator.go
- services/sidecar/rollup/services/validator/validator.go
- Use correct head in dissemination/validator
- Use block hash instead of root (to be changed later to a versioned commitment)
> Misc sidecar fixes

- .github/workflows/e2e.yml
- .github/workflows/release-snapshot.yml
- .gitignore
Core changes:
- gitignore extension to exclude IDE's stuff
- staled changes cherry-picked from #200 
Notes:
- n/a
> gitignore extension to exclude IDE's stuff; git cache

- services/sidecar/.gitignore
- services/sidecar/bindings/gen.go
Core changes:
- Add L1Oracle bindings to sidecar
> Add L1Oracle bindings to sidecar

- services/sidecar/cmd/sidecar/main.go
The `From` address must be set in the txmgr config
> Fix txmgr bug

- contracts/test/bridge/Common.t.sol
- contracts/test/bridge/L1StandardBridge.t.sol
- contracts/test/bridge/L2StandardBridge.t.sol
Core changes:
- calculate the deposit hash in the test instead of hardcoding it
- deploy `L2Portal` contract at the pre-deploy address during testing
> fix forge tests

- config/example/.genesis.env
- config/example/base_sp_rollup.json
- config/local_devnet/base_sp_rollup.json
- config/local_docker/base_sp_rollup.json
- docs/development.md
- sbin/start_l1.sh
- services/sidecar/cmd/sidecar/main.go
- services/sidecar/go.mod
- services/sidecar/rollup/derivation/batch_builder.go
- services/sidecar/rollup/derivation/batch_v0_encoder.go
- services/sidecar/rollup/rpc/bridge/serialization.go
- services/sidecar/rollup/rpc/eth/txmgr/config.go
- services/sidecar/rollup/rpc/eth/txmgr/metrics/noop.go
- services/sidecar/rollup/rpc/eth/txmgr/send_state.go
- services/sidecar/rollup/rpc/eth/txmgr/send_state_test.go
- services/sidecar/rollup/rpc/eth/txmgr/tx_mgr.go
- services/sidecar/rollup/services/config.go
- services/sidecar/rollup/services/disseminator/batch_disseminator.go
- services/sidecar/rollup/services/flags.go
- Unpack inputs correctly
- Trigger sub-batch closing correctly (emptiness check was incorrect previously)
- Use the right l1 chain ID for geth
- update txmgr to the latest upstream (and add some tests)
- add some basic param validation to `config.go`
> Fix disseminator input unpacking (and other misc bugfixes)

- sbin/deploy_l1_contracts.sh
Core changes:
- Describe changes here
Notes:
- Write notes here
> fix l1 deploy

- contracts/src/Rollup.sol
Correctly constrain the sibling assertions
> [contracts] [bugfix] Constrain sibling assertions correctly

- docs/development.md
- sbin/start_sp_geth.sh
- sbin/start_sp_magi.sh
- services/sidecar/rollup/derivation/batch_builder.go
- Update magi submodule
- Some minor naming/doc/script fixes
> [misc] Update submodule and minor fixes

- ops/deployer/deployer.go
- ops/predeploys/predeploys.go
Core changes:
- Fix genesis generation for predeploy proxy code
- Now predeploys are with correct proxy
> Fix genesis generation for predeploy proxy code

- docs/development.md
> add shfmt as dependency in development.md
