clients/geth/specular/rollup/services/sequencer/batcher.go
clients/geth/specular/rollup/services/validator/validator.go

Core changes:
- Make all calls to `WriteBlockAndSetHead` emit head event
Notes:
- To make the transaction pool work correctly, chain head event needs to be emitted
- The worker will not start now since the configuration has changed long time ago

Make WriteBlockAndSetHead emit head event

---

contracts/src/Rollup.sol

The `if` statement logic to validate input for `Rollup.initialize` has been fixed to revert for any address(0) that is supplied.
```
if (_owner == address(0) && _sequencerInbox == address(0) && _verifier == address(0)) {
revert ZeroAddress();
}
```
```
if (_owner == address(0) ||  _sequencerInbox == address(0) || _verifier == address(0)) {
revert ZeroAddress();
}
```

Fix `Rollup` initialize function 

---

clients/geth/specular/cmd/geth/main.go
clients/geth/specular/cmd/utils/flags.go
clients/geth/specular/rollup/service.go
clients/geth/specular/rollup/services/base.go
clients/geth/specular/rollup/services/config.go
clients/geth/specular/rollup/services/indexer/indexer.go
clients/geth/specular/rollup/services/sequencer/batcher.go
clients/geth/specular/rollup/services/sequencer/sequencer.go
clients/geth/specular/rollup/services/sync.go
clients/geth/specular/rollup/services/validator/validator.go
clients/geth/specular/rollup/test-node/.gitignore
clients/geth/specular/rollup/test-node/attach_indexer.sh
clients/geth/specular/rollup/test-node/clean.sh
clients/geth/specular/rollup/test-node/import_accounts.sh
clients/geth/specular/rollup/test-node/init.sh
clients/geth/specular/rollup/test-node/start_indexer.sh
clients/geth/specular/rollup/test-node/start_validator.sh

Dependencies:
- #11 
- #12 
Core changes:
- Refactor validator's inbox syncing, move to base service
- Validator behavior change: executes transactions when they are posted in the inbox instead of when new assertions published
- `BaseService.SyncInbox` allows a service to sync past sequenced transactions
- `BaseService.SyncLoop` allows a service to sync past sequenced transactions as well as watch ongoing ones
- `Indexer` is a service that only syncs sequenced transactions to its local blockchain, it won't participate in the validation/challenge
- It is designed for the block explorer when used with archive flag
Notes:
- Assertion/Stake sync is not implemented in this pr so the sequencer/validator still can not be restarted

Inbox sync & indexer service

---

contracts/test/SequencerInbox.t.sol

To do away with the error popping up due to wrong import of `EmptyBatch` error in the contract tests.

Correct import of EmptyBatch error

---

contracts/src/Rollup.sol
contracts/test/SequencerInbox.t.sol

1. Rollup.removeStake function has a bug that leads to loss of funds of staker. The value transferred to the staker would always be 0.  
2. Rollup.removeStake function has a bug.
3. 
```
/**
* function removeStake(address stakerAddress) external override {
*             requireStaked(stakerAddress);
*             // Require that staker is staked on a confirmed assertion.
*             Staker storage staker = stakers[stakerAddress];
*             if (staker.assertionID > lastConfirmedAssertionID) {
*                 revert StakedOnUnconfirmedAssertion();
*             }
*             deleteStaker(stakerAddress);
*             // Note: we don't need to modify assertion state because you can only unstake from a confirmed assertion.
*             (bool success,) = stakerAddress.call{value: …
```

Fixing critical issues in Rollup contract

---

clients/geth/specular/rollup/services/sequencer/sequencer.go
clients/geth/specular/rollup/services/validator/validator.go

This PR handles the errors whenever the sequencer can't send a transaction because of insufficient funds.

handle low-l1 eth errors

---

clients/geth/specular/rollup/services/sequencer/sequencer.go
clients/geth/specular/rollup/services/validator/validator.go

Fixes a typo in sequencer and validator `errors.Is`

Handle low l1 eth - fix typo in #32

---

.husky/pre-commit
contracts/.lintstagedrc.json
contracts/README.md
contracts/package.json
contracts/src/SequencerInbox.sol
contracts/yarn.lock

This PR sets up https://www.npmjs.com/package/lint-staged to Run linters against staged git files and don't let unnecessary changes slip into code base.

Setting lint-staged

---

.github/workflows/slither.yml

Fixing the `fatal: detected dubious ownership in repository at '/github/workspace'` issue using  [dev-git-safe-workspace](https://github.com/crytic/slither-action/issues/49) branch from slither-action.

Fix slither workflow dubious ownership issue (temporary patch)

---

contracts/deploy/00_deploy_SequencerInbox.ts
contracts/deploy/01_deploy_Verifier.ts
contracts/deploy/02_deploy_Rollup.ts
contracts/hardhat.config.ts

Core changes:
- Use deployment file instead of upgrade manifest to determine previously deployed proxy addresses.
Notes:
- During deployment the `proxies` array of upgrade manifest will be updated out of order if it is not a fresh deployment, causing mismatching of initialize arguments of rollup contract.

Fix rollup proxy deployment

---

.github/workflows/slither.yml

Bumping the slither action version to v0.3.0 as the temporary patch got merged in this new version. https://github.com/crytic/slither-action/releases/tag/v0.3.0

bump slither-action to v0.3.0

---

contracts/deploy/00_deploy_SequencerInbox.ts
contracts/deploy/01_deploy_Verifier.ts
contracts/deploy/02_deploy_Rollup.ts

removing `from` option from `deployProxy` in all deployment scripts

remove unnecessary code from deployment scripts

---

.husky/pre-commit

update precommit to builds go files only when changes introduced in `clients/geth/specular` directory

Update precommit - build go code only on changes

---

clients/geth/specular/sbin/export_genesis.sh
contracts/deploy/02_deploy_Rollup.ts

Core changes:
- currently the genesis hash is hardcoded in the deploy script, this adds a script to export the genesis hash from the sequencer and uses that during deployment

automate genesis hash input

---

clients/geth/specular/bindings/ISequencerInbox.go
clients/geth/specular/rollup/client/l1client.go
clients/geth/specular/rollup/services/base.go
clients/geth/specular/rollup/services/sequencer/sequencer.go
clients/geth/specular/rollup/services/validator/validator.go
clients/geth/specular/rollup/types/tx_batch.go
contracts/src/ISequencerInbox.sol
contracts/src/SequencerInbox.sol
contracts/test/Rollup.t.sol
contracts/test/SequencerInbox.t.sol

In a `TxBatch` we no longer store the block number in every context. Instead we only store the first block number of the batch and can reconstruct the other block numbers by incrementing.
We can see this leads to a small reduction of gas cost
```
Blocks in Batch: 10
TXs per Block:   30
only first block number of the batch:
(runs: 10, μ: 1997645152, ~: 1997645110)
only first block number of the batch, context struct:
(runs: 10, μ: 1997787298, ~: 1997787299)
block number in every context:
(runs: 10, μ: 1997722666, ~: 1997722664)
```
```
Blocks in Batch: 5
TXs per Block:   30
only first block number of the batch:
(runs: 10, μ: 143393358, ~: 143393361)
only first block number of the batch, context struct:
(runs: 10, μ: 143414539, ~: 143414585)
block number in every context:
(runs: 10, μ: …
```

Remove block# redundancy in appendTxBatch

---

contracts/src/IRollup.sol
contracts/src/Rollup.sol
contracts/src/challenge/SymChallenge.sol

Allow `Rollup.sol` to be reconfigured without upgrading the contract when possible. Emits a `ConfigChanged` event when a config param is successfully changed.

Allow contract configurability w/o upgrade

---

clients/geth/specular/rollup/services/validator/validator.go

Core changes:
The current validator is throwing `errAssertionOverflowedLocalInbox` when validating. 
This is happening because there is an event on `assertionEventCh` (caused by the sequencer creating an on chain assertion) which triggers a validation of the assertion before the validator has committed the new batch locally.
The proposed solution is to leave the assertion pending after the `assertionEventCh` event and only validate them once the batch is committed locally.

Avoid validating assertions before committing them locally

---

contracts/package.json
contracts/scripts/pause.ts
contracts/src/Rollup.sol
contracts/src/SequencerInbox.sol
contracts/src/bridge/L1Oracle.sol
contracts/src/bridge/L1Portal.sol
contracts/src/bridge/L1StandardBridge.sol
contracts/src/bridge/L2Portal.sol
contracts/src/bridge/L2StandardBridge.sol
contracts/src/bridge/StandardBridge.sol
contracts/src/pre-deploy/Faucet.sol
contracts/test/Rollup.t.sol
contracts/test/SequencerInbox.t.sol
pnpm-lock.yaml

Core changes:
- Implement `PausableUpgradeable` from OpenZeppelin for the SequencerInbox, Rollup and Bridge contracts
- Use modifier `whenPaused` to decorate `_authorizeUpgrade` so that upgrade can only be authorized when paused.
- Use modifier `whenNotPaused` to decorate particular functions that would progress the state of the contracts such that new consensus must be arrived at. Namely, prevent bridge transfers (requires confirmation), prevent new assertions from being created (requiring confirmation), preventing new stakers from staking and prevent new transaction batches from being appended (as they need to be asserted and confirmed),
- Testing some basic functionalities are correctly disabled when the contracts are paused.
- Adds a method `hasConsensus` for checking if `Rollup.sol` …

Add Ability to Pause/Unpause Contracts

---

contracts/README.md

the new `.env` setup caused some confusion, this adds a comment about it in the readme

update contracts readme

---

contracts/test/bridge/Common.t.sol
contracts/test/bridge/L1StandardBridge.t.sol
contracts/test/bridge/L2StandardBridge.t.sol
contracts/test/bridge/StandardBridge.t.sol

Core changes:
- adds unit tests for the standard bridge contracts
- the test try to emulate the approach taken by [optimism](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock/test)
- depends on #131

standard bridge unit tests

---

contracts/scripts/bridge/standard_bridge_retry.ts
contracts/src/bridge/L1Portal.sol
contracts/src/bridge/L2Portal.sol

Allow users to retry finalisation if the transaction fails. this automatically gives us retryability for the StandardBridge as well.
This should be safe since a transaction can only be replayed if it reverted and thus didn't cause a state change.  See [optimism implementation](https://github.com/ethereum-optimism/optimism/blob/05bacdc2af08c8ee16ddefcbf9c4f595e78c5f6f/packages/contracts-bedrock/src/universal/CrossDomainMessenger.sol#L283) for a similar check.

portal retryability

---

config/package.json

Core changes:
- Add `"private": true` to the `specular-config-generation` package.

specular-config-generation: Mark as private

---

contracts/scripts/e2e/bridge/test_standard_bridge_erc20.ts
contracts/scripts/e2e/bridge/test_standard_bridge_withdraw_eth.ts
contracts/scripts/e2e/utils.ts
e2e/sbin/test.sh

- Removes hardcoded ABI from test script.
- Removes log prefix when running test script to preserve exit code.
Comment: The same change could be implemented in the relayer TS service where it is originally from.

fix appendTxBatch signature and preserve exit code

---

sbin/compile_contracts.sh
sbin/configure.sh
sbin/start_l1.sh

Fix the following error in the compile_contracts script:
```
sbin/compile_contracts.sh: 18: /home/user/specular/specular/sbin/configure.sh: source: not found
```
On my linux distribution, the `sh` shell is symlinked to `dash` which doesn't support the `source` builtin.
```
ls -l `which sh`
lrwxrwxrwx 1 root root 4 Jun  9  2022 /usr/bin/sh -> dash
```
I replaced the shebang in `sbin/compile_contracts.sh` with `!/bin/bash`, which fixes the issue.
I also replaced our use of `source` with the posix standard `.` for portability.

replace source with .

---

contracts/README.md
package.json
pnpm-lock.yaml

Core changes:
- Missing dependencies to run `create_genesis.sh` out-of-the-box
- README update on the contracts to include `fondry install`
- (no change) done review if there are any unnecessary pnpm ts-node installs (which is not dev-dependency)

Missing dependencies for create genesis script

---

sbin/start_geth.sh

Follow up to this [PR](https://github.com/SpecularL2/go-ethereum/pull/9): which helps enable faster block production by allowing geth to produce sealing blocks faster.
This PR changes the `start_geth` script to start our L2 execution engine (specular-geth) with `--miner.commit=0`. Geth will sanitize this value to the lowest allowed recommit interval (100ms).
We can confirm this change works because geth now starts with this line:
```
WARN [10-19|22:35:58.148] Sanitizing miner recommit interval       provided=0s updated=100ms
```
This change could affect performance at startup, but if geth isn't able to fill blocks within this interval, there is logic to adjust this value higher.

start geth with lower recommit interval

---

config/local_devnet/base_genesis.json

Follow up to this [PR](https://github.com/MoonShiesty/go-ethereum/tree/gas-limit) to enableL2GasLimitApi in the chain config via `genesis.json`. I also updated sp-geth to 
when this feature is enabled, sp-geth should log this on startup:
```
Consensus: L2 gas limit API enabled
```
I also updated the sp-geth submodule to the latest

enableL2GasLimitApi

---

contracts/deploy/l2/01_deploy_L1Oracle.ts
contracts/src/bridge/L1Oracle.sol
contracts/test/bridge/Common.t.sol

Core changes:
- Add `timestamp` and `hash` field
- Remove `L1OracleValuesUpdated` event

Update L1Oracle contract to latest derivation specs

---

services/sidecar/rollup/services/config.go

if a service like validator / sequencer is disabled, we should allow both the PK flag and the clef endpoint to be empty

don't require PK if service is not activated

---

contracts/src/bridge/L1Oracle.sol

Core changes:
- Add a `require` state to ensure L1Oracle block number increases monotonically
- So that the sequencer can not modify the oracle values in the middle of the batch undetected

Ensure L1Oracle block number increases monotonically

---

contracts/src/IRollup.sol
contracts/src/Rollup.sol
contracts/src/bridge/L1Portal.sol
contracts/test/Rollup.t.sol
services/sidecar/rollup/rpc/bridge/serialization.go
services/sidecar/rollup/rpc/bridge/tx_mgr.go
services/sidecar/rollup/services/validator/interface.go
services/sidecar/rollup/services/validator/state_commitment.go
services/sidecar/rollup/services/validator/validator.go
services/sidecar/rollup/types/assertion.go

Version assertion data, which currently is currently equivalent to vmHash.
- Describe changes here
Prepend a version byte to assertion data, and store as a blob and modify validator to publish new versioned assertion data blob format.
- Write notes here
These changes increase the size of `Rollup.sol` over the transaction size limit (by ~100 with optimizer on and 1 run). We'll have to split up `Rollup.sol` to deploy these changes.
The decoding versioned assertion data cannot revert or validators will be unable to challange assertions with invalid encoding.

Version assertion
